#!/usr/bin/env bash

cp -v ./build/d3.github.com/colorbrewer.v1.css docs/public/colorbrewer.v1.css
cp -v ./build/d3.github.com/colorbrewer.v1.js docs/public/colorbrewer.v1.js
cp -v ./build/d3.github.com/colorbrewer.v1.min.js docs/public/colorbrewer.v1.min.js
cp -v ./build/d3.github.com/d3-array.v0.6.js docs/public/d3-array.v0.6.js
cp -v ./build/d3.github.com/d3-array.v0.6.min.js docs/public/d3-array.v0.6.min.js
cp -v ./build/d3.github.com/d3-array.v0.7.js docs/public/d3-array.v0.7.js
cp -v ./build/d3.github.com/d3-array.v0.7.min.js docs/public/d3-array.v0.7.min.js
cp -v ./build/d3.github.com/d3-array.v0.8.js docs/public/d3-array.v0.8.js
cp -v ./build/d3.github.com/d3-array.v0.8.min.js docs/public/d3-array.v0.8.min.js
cp -v ./build/d3.github.com/d3-array.v1.js docs/public/d3-array.v1.js
cp -v ./build/d3.github.com/d3-array.v1.min.js docs/public/d3-array.v1.min.js
cp -v ./build/d3.github.com/d3-array.v2.js docs/public/d3-array.v2.js
cp -v ./build/d3.github.com/d3-array.v2.min.js docs/public/d3-array.v2.min.js
cp -v ./build/d3.github.com/d3-array.v3.js docs/public/d3-array.v3.js
cp -v ./build/d3.github.com/d3-array.v3.min.js docs/public/d3-array.v3.min.js
cp -v ./build/d3.github.com/d3-axis.v0.1.js docs/public/d3-axis.v0.1.js
cp -v ./build/d3.github.com/d3-axis.v0.1.min.js docs/public/d3-axis.v0.1.min.js
cp -v ./build/d3.github.com/d3-axis.v0.2.js docs/public/d3-axis.v0.2.js
cp -v ./build/d3.github.com/d3-axis.v0.2.min.js docs/public/d3-axis.v0.2.min.js
cp -v ./build/d3.github.com/d3-axis.v0.3.js docs/public/d3-axis.v0.3.js
cp -v ./build/d3.github.com/d3-axis.v0.3.min.js docs/public/d3-axis.v0.3.min.js
cp -v ./build/d3.github.com/d3-axis.v0.4.js docs/public/d3-axis.v0.4.js
cp -v ./build/d3.github.com/d3-axis.v0.4.min.js docs/public/d3-axis.v0.4.min.js
cp -v ./build/d3.github.com/d3-axis.v1.js docs/public/d3-axis.v1.js
cp -v ./build/d3.github.com/d3-axis.v1.min.js docs/public/d3-axis.v1.min.js
cp -v ./build/d3.github.com/d3-axis.v2.js docs/public/d3-axis.v2.js
cp -v ./build/d3.github.com/d3-axis.v2.min.js docs/public/d3-axis.v2.min.js
cp -v ./build/d3.github.com/d3-axis.v3.js docs/public/d3-axis.v3.js
cp -v ./build/d3.github.com/d3-axis.v3.min.js docs/public/d3-axis.v3.min.js
cp -v ./build/d3.github.com/d3-brush.v0.1.js docs/public/d3-brush.v0.1.js
cp -v ./build/d3.github.com/d3-brush.v0.1.min.js docs/public/d3-brush.v0.1.min.js
cp -v ./build/d3.github.com/d3-brush.v0.2.js docs/public/d3-brush.v0.2.js
cp -v ./build/d3.github.com/d3-brush.v0.2.min.js docs/public/d3-brush.v0.2.min.js
cp -v ./build/d3.github.com/d3-brush.v1.js docs/public/d3-brush.v1.js
cp -v ./build/d3.github.com/d3-brush.v1.min.js docs/public/d3-brush.v1.min.js
cp -v ./build/d3.github.com/d3-brush.v2.js docs/public/d3-brush.v2.js
cp -v ./build/d3.github.com/d3-brush.v2.min.js docs/public/d3-brush.v2.min.js
cp -v ./build/d3.github.com/d3-brush.v3.js docs/public/d3-brush.v3.js
cp -v ./build/d3.github.com/d3-brush.v3.min.js docs/public/d3-brush.v3.min.js
cp -v ./build/d3.github.com/d3-chord.v0.0.js docs/public/d3-chord.v0.0.js
cp -v ./build/d3.github.com/d3-chord.v0.0.min.js docs/public/d3-chord.v0.0.min.js
cp -v ./build/d3.github.com/d3-chord.v1.js docs/public/d3-chord.v1.js
cp -v ./build/d3.github.com/d3-chord.v1.min.js docs/public/d3-chord.v1.min.js
cp -v ./build/d3.github.com/d3-chord.v2.js docs/public/d3-chord.v2.js
cp -v ./build/d3.github.com/d3-chord.v2.min.js docs/public/d3-chord.v2.min.js
cp -v ./build/d3.github.com/d3-chord.v3.js docs/public/d3-chord.v3.js
cp -v ./build/d3.github.com/d3-chord.v3.min.js docs/public/d3-chord.v3.min.js
cp -v ./build/d3.github.com/d3-collection.v0.1.js docs/public/d3-collection.v0.1.js
cp -v ./build/d3.github.com/d3-collection.v0.1.min.js docs/public/d3-collection.v0.1.min.js
cp -v ./build/d3.github.com/d3-collection.v0.2.js docs/public/d3-collection.v0.2.js
cp -v ./build/d3.github.com/d3-collection.v0.2.min.js docs/public/d3-collection.v0.2.min.js
cp -v ./build/d3.github.com/d3-collection.v0.3.js docs/public/d3-collection.v0.3.js
cp -v ./build/d3.github.com/d3-collection.v0.3.min.js docs/public/d3-collection.v0.3.min.js
cp -v ./build/d3.github.com/d3-collection.v1.js docs/public/d3-collection.v1.js
cp -v ./build/d3.github.com/d3-collection.v1.min.js docs/public/d3-collection.v1.min.js
cp -v ./build/d3.github.com/d3-color.v0.3.js docs/public/d3-color.v0.3.js
cp -v ./build/d3.github.com/d3-color.v0.3.min.js docs/public/d3-color.v0.3.min.js
cp -v ./build/d3.github.com/d3-color.v0.4.js docs/public/d3-color.v0.4.js
cp -v ./build/d3.github.com/d3-color.v0.4.min.js docs/public/d3-color.v0.4.min.js
cp -v ./build/d3.github.com/d3-color.v0.5.js docs/public/d3-color.v0.5.js
cp -v ./build/d3.github.com/d3-color.v0.5.min.js docs/public/d3-color.v0.5.min.js
cp -v ./build/d3.github.com/d3-color.v1.js docs/public/d3-color.v1.js
cp -v ./build/d3.github.com/d3-color.v1.min.js docs/public/d3-color.v1.min.js
cp -v ./build/d3.github.com/d3-color.v2.js docs/public/d3-color.v2.js
cp -v ./build/d3.github.com/d3-color.v2.min.js docs/public/d3-color.v2.min.js
cp -v ./build/d3.github.com/d3-color.v3.js docs/public/d3-color.v3.js
cp -v ./build/d3.github.com/d3-color.v3.min.js docs/public/d3-color.v3.min.js
cp -v ./build/d3.github.com/d3-contour.v0.0.js docs/public/d3-contour.v0.0.js
cp -v ./build/d3.github.com/d3-contour.v0.0.min.js docs/public/d3-contour.v0.0.min.js
cp -v ./build/d3.github.com/d3-contour.v1.js docs/public/d3-contour.v1.js
cp -v ./build/d3.github.com/d3-contour.v1.min.js docs/public/d3-contour.v1.min.js
cp -v ./build/d3.github.com/d3-contour.v2.js docs/public/d3-contour.v2.js
cp -v ./build/d3.github.com/d3-contour.v2.min.js docs/public/d3-contour.v2.min.js
cp -v ./build/d3.github.com/d3-contour.v3.js docs/public/d3-contour.v3.js
cp -v ./build/d3.github.com/d3-contour.v3.min.js docs/public/d3-contour.v3.min.js
cp -v ./build/d3.github.com/d3-contour.v4.js docs/public/d3-contour.v4.js
cp -v ./build/d3.github.com/d3-contour.v4.min.js docs/public/d3-contour.v4.min.js
cp -v ./build/d3.github.com/d3-dispatch.v0.2.js docs/public/d3-dispatch.v0.2.js
cp -v ./build/d3.github.com/d3-dispatch.v0.2.min.js docs/public/d3-dispatch.v0.2.min.js
cp -v ./build/d3.github.com/d3-dispatch.v0.3.js docs/public/d3-dispatch.v0.3.js
cp -v ./build/d3.github.com/d3-dispatch.v0.3.min.js docs/public/d3-dispatch.v0.3.min.js
cp -v ./build/d3.github.com/d3-dispatch.v0.4.js docs/public/d3-dispatch.v0.4.js
cp -v ./build/d3.github.com/d3-dispatch.v0.4.min.js docs/public/d3-dispatch.v0.4.min.js
cp -v ./build/d3.github.com/d3-dispatch.v0.5.js docs/public/d3-dispatch.v0.5.js
cp -v ./build/d3.github.com/d3-dispatch.v0.5.min.js docs/public/d3-dispatch.v0.5.min.js
cp -v ./build/d3.github.com/d3-dispatch.v1.js docs/public/d3-dispatch.v1.js
cp -v ./build/d3.github.com/d3-dispatch.v1.min.js docs/public/d3-dispatch.v1.min.js
cp -v ./build/d3.github.com/d3-dispatch.v2.js docs/public/d3-dispatch.v2.js
cp -v ./build/d3.github.com/d3-dispatch.v2.min.js docs/public/d3-dispatch.v2.min.js
cp -v ./build/d3.github.com/d3-dispatch.v3.js docs/public/d3-dispatch.v3.js
cp -v ./build/d3.github.com/d3-dispatch.v3.min.js docs/public/d3-dispatch.v3.min.js
cp -v ./build/d3.github.com/d3-drag.v0.0.js docs/public/d3-drag.v0.0.js
cp -v ./build/d3.github.com/d3-drag.v0.0.min.js docs/public/d3-drag.v0.0.min.js
cp -v ./build/d3.github.com/d3-drag.v0.1.js docs/public/d3-drag.v0.1.js
cp -v ./build/d3.github.com/d3-drag.v0.1.min.js docs/public/d3-drag.v0.1.min.js
cp -v ./build/d3.github.com/d3-drag.v0.2.js docs/public/d3-drag.v0.2.js
cp -v ./build/d3.github.com/d3-drag.v0.2.min.js docs/public/d3-drag.v0.2.min.js
cp -v ./build/d3.github.com/d3-drag.v0.3.js docs/public/d3-drag.v0.3.js
cp -v ./build/d3.github.com/d3-drag.v0.3.min.js docs/public/d3-drag.v0.3.min.js
cp -v ./build/d3.github.com/d3-drag.v1.js docs/public/d3-drag.v1.js
cp -v ./build/d3.github.com/d3-drag.v1.min.js docs/public/d3-drag.v1.min.js
cp -v ./build/d3.github.com/d3-drag.v2.js docs/public/d3-drag.v2.js
cp -v ./build/d3.github.com/d3-drag.v2.min.js docs/public/d3-drag.v2.min.js
cp -v ./build/d3.github.com/d3-drag.v3.js docs/public/d3-drag.v3.js
cp -v ./build/d3.github.com/d3-drag.v3.min.js docs/public/d3-drag.v3.min.js
cp -v ./build/d3.github.com/d3-dsv.v0.1.js docs/public/d3-dsv.v0.1.js
cp -v ./build/d3.github.com/d3-dsv.v0.1.min.js docs/public/d3-dsv.v0.1.min.js
cp -v ./build/d3.github.com/d3-dsv.v0.2.js docs/public/d3-dsv.v0.2.js
cp -v ./build/d3.github.com/d3-dsv.v0.2.min.js docs/public/d3-dsv.v0.2.min.js
cp -v ./build/d3.github.com/d3-dsv.v0.3.js docs/public/d3-dsv.v0.3.js
cp -v ./build/d3.github.com/d3-dsv.v0.3.min.js docs/public/d3-dsv.v0.3.min.js
cp -v ./build/d3.github.com/d3-dsv.v0.4.js docs/public/d3-dsv.v0.4.js
cp -v ./build/d3.github.com/d3-dsv.v0.4.min.js docs/public/d3-dsv.v0.4.min.js
cp -v ./build/d3.github.com/d3-dsv.v1.js docs/public/d3-dsv.v1.js
cp -v ./build/d3.github.com/d3-dsv.v1.min.js docs/public/d3-dsv.v1.min.js
cp -v ./build/d3.github.com/d3-dsv.v2.js docs/public/d3-dsv.v2.js
cp -v ./build/d3.github.com/d3-dsv.v2.min.js docs/public/d3-dsv.v2.min.js
cp -v ./build/d3.github.com/d3-dsv.v3.js docs/public/d3-dsv.v3.js
cp -v ./build/d3.github.com/d3-dsv.v3.min.js docs/public/d3-dsv.v3.min.js
cp -v ./build/d3.github.com/d3-ease.v0.3.js docs/public/d3-ease.v0.3.js
cp -v ./build/d3.github.com/d3-ease.v0.3.min.js docs/public/d3-ease.v0.3.min.js
cp -v ./build/d3.github.com/d3-ease.v0.4.js docs/public/d3-ease.v0.4.js
cp -v ./build/d3.github.com/d3-ease.v0.4.min.js docs/public/d3-ease.v0.4.min.js
cp -v ./build/d3.github.com/d3-ease.v0.5.js docs/public/d3-ease.v0.5.js
cp -v ./build/d3.github.com/d3-ease.v0.5.min.js docs/public/d3-ease.v0.5.min.js
cp -v ./build/d3.github.com/d3-ease.v0.6.js docs/public/d3-ease.v0.6.js
cp -v ./build/d3.github.com/d3-ease.v0.6.min.js docs/public/d3-ease.v0.6.min.js
cp -v ./build/d3.github.com/d3-ease.v0.7.js docs/public/d3-ease.v0.7.js
cp -v ./build/d3.github.com/d3-ease.v0.7.min.js docs/public/d3-ease.v0.7.min.js
cp -v ./build/d3.github.com/d3-ease.v0.8.js docs/public/d3-ease.v0.8.js
cp -v ./build/d3.github.com/d3-ease.v0.8.min.js docs/public/d3-ease.v0.8.min.js
cp -v ./build/d3.github.com/d3-ease.v1.js docs/public/d3-ease.v1.js
cp -v ./build/d3.github.com/d3-ease.v1.min.js docs/public/d3-ease.v1.min.js
cp -v ./build/d3.github.com/d3-ease.v2.js docs/public/d3-ease.v2.js
cp -v ./build/d3.github.com/d3-ease.v2.min.js docs/public/d3-ease.v2.min.js
cp -v ./build/d3.github.com/d3-ease.v3.js docs/public/d3-ease.v3.js
cp -v ./build/d3.github.com/d3-ease.v3.min.js docs/public/d3-ease.v3.min.js
cp -v ./build/d3.github.com/d3-fetch.v0.js docs/public/d3-fetch.v0.js
cp -v ./build/d3.github.com/d3-fetch.v0.min.js docs/public/d3-fetch.v0.min.js
cp -v ./build/d3.github.com/d3-fetch.v1.js docs/public/d3-fetch.v1.js
cp -v ./build/d3.github.com/d3-fetch.v1.min.js docs/public/d3-fetch.v1.min.js
cp -v ./build/d3.github.com/d3-fetch.v2.js docs/public/d3-fetch.v2.js
cp -v ./build/d3.github.com/d3-fetch.v2.min.js docs/public/d3-fetch.v2.min.js
cp -v ./build/d3.github.com/d3-fetch.v3.js docs/public/d3-fetch.v3.js
cp -v ./build/d3.github.com/d3-fetch.v3.min.js docs/public/d3-fetch.v3.min.js
cp -v ./build/d3.github.com/d3-force.v0.0.js docs/public/d3-force.v0.0.js
cp -v ./build/d3.github.com/d3-force.v0.0.min.js docs/public/d3-force.v0.0.min.js
cp -v ./build/d3.github.com/d3-force.v0.1.js docs/public/d3-force.v0.1.js
cp -v ./build/d3.github.com/d3-force.v0.1.min.js docs/public/d3-force.v0.1.min.js
cp -v ./build/d3.github.com/d3-force.v0.2.js docs/public/d3-force.v0.2.js
cp -v ./build/d3.github.com/d3-force.v0.2.min.js docs/public/d3-force.v0.2.min.js
cp -v ./build/d3.github.com/d3-force.v0.3.js docs/public/d3-force.v0.3.js
cp -v ./build/d3.github.com/d3-force.v0.3.min.js docs/public/d3-force.v0.3.min.js
cp -v ./build/d3.github.com/d3-force.v0.4.js docs/public/d3-force.v0.4.js
cp -v ./build/d3.github.com/d3-force.v0.4.min.js docs/public/d3-force.v0.4.min.js
cp -v ./build/d3.github.com/d3-force.v0.5.js docs/public/d3-force.v0.5.js
cp -v ./build/d3.github.com/d3-force.v0.5.min.js docs/public/d3-force.v0.5.min.js
cp -v ./build/d3.github.com/d3-force.v0.6.js docs/public/d3-force.v0.6.js
cp -v ./build/d3.github.com/d3-force.v0.6.min.js docs/public/d3-force.v0.6.min.js
cp -v ./build/d3.github.com/d3-force.v0.7.js docs/public/d3-force.v0.7.js
cp -v ./build/d3.github.com/d3-force.v0.7.min.js docs/public/d3-force.v0.7.min.js
cp -v ./build/d3.github.com/d3-force.v1.js docs/public/d3-force.v1.js
cp -v ./build/d3.github.com/d3-force.v1.min.js docs/public/d3-force.v1.min.js
cp -v ./build/d3.github.com/d3-force.v2.js docs/public/d3-force.v2.js
cp -v ./build/d3.github.com/d3-force.v2.min.js docs/public/d3-force.v2.min.js
cp -v ./build/d3.github.com/d3-force.v3.js docs/public/d3-force.v3.js
cp -v ./build/d3.github.com/d3-force.v3.min.js docs/public/d3-force.v3.min.js
cp -v ./build/d3.github.com/d3-format.v0.4.js docs/public/d3-format.v0.4.js
cp -v ./build/d3.github.com/d3-format.v0.4.min.js docs/public/d3-format.v0.4.min.js
cp -v ./build/d3.github.com/d3-format.v0.5.js docs/public/d3-format.v0.5.js
cp -v ./build/d3.github.com/d3-format.v0.5.min.js docs/public/d3-format.v0.5.min.js
cp -v ./build/d3.github.com/d3-format.v0.6.js docs/public/d3-format.v0.6.js
cp -v ./build/d3.github.com/d3-format.v0.6.min.js docs/public/d3-format.v0.6.min.js
cp -v ./build/d3.github.com/d3-format.v1.js docs/public/d3-format.v1.js
cp -v ./build/d3.github.com/d3-format.v1.min.js docs/public/d3-format.v1.min.js
cp -v ./build/d3.github.com/d3-format.v2.js docs/public/d3-format.v2.js
cp -v ./build/d3.github.com/d3-format.v2.min.js docs/public/d3-format.v2.min.js
cp -v ./build/d3.github.com/d3-format.v3.js docs/public/d3-format.v3.js
cp -v ./build/d3.github.com/d3-format.v3.min.js docs/public/d3-format.v3.min.js
cp -v ./build/d3.github.com/d3-geo-projection.v1.js docs/public/d3-geo-projection.v1.js
cp -v ./build/d3.github.com/d3-geo-projection.v1.min.js docs/public/d3-geo-projection.v1.min.js
cp -v ./build/d3.github.com/d3-geo-projection.v2.js docs/public/d3-geo-projection.v2.js
cp -v ./build/d3.github.com/d3-geo-projection.v2.min.js docs/public/d3-geo-projection.v2.min.js
cp -v ./build/d3.github.com/d3-geo-projection.v3.js docs/public/d3-geo-projection.v3.js
cp -v ./build/d3.github.com/d3-geo-projection.v3.min.js docs/public/d3-geo-projection.v3.min.js
cp -v ./build/d3.github.com/d3-geo-projection.v4.js docs/public/d3-geo-projection.v4.js
cp -v ./build/d3.github.com/d3-geo-projection.v4.min.js docs/public/d3-geo-projection.v4.min.js
cp -v ./build/d3.github.com/d3-geo.v0.0.js docs/public/d3-geo.v0.0.js
cp -v ./build/d3.github.com/d3-geo.v0.0.min.js docs/public/d3-geo.v0.0.min.js
cp -v ./build/d3.github.com/d3-geo.v0.1.js docs/public/d3-geo.v0.1.js
cp -v ./build/d3.github.com/d3-geo.v0.1.min.js docs/public/d3-geo.v0.1.min.js
cp -v ./build/d3.github.com/d3-geo.v1.js docs/public/d3-geo.v1.js
cp -v ./build/d3.github.com/d3-geo.v1.min.js docs/public/d3-geo.v1.min.js
cp -v ./build/d3.github.com/d3-geo.v2.js docs/public/d3-geo.v2.js
cp -v ./build/d3.github.com/d3-geo.v2.min.js docs/public/d3-geo.v2.min.js
cp -v ./build/d3.github.com/d3-geo.v3.js docs/public/d3-geo.v3.js
cp -v ./build/d3.github.com/d3-geo.v3.min.js docs/public/d3-geo.v3.min.js
cp -v ./build/d3.github.com/d3-hexbin.v0.2.js docs/public/d3-hexbin.v0.2.js
cp -v ./build/d3.github.com/d3-hexbin.v0.2.min.js docs/public/d3-hexbin.v0.2.min.js
cp -v ./build/d3.github.com/d3-hexbin.v1.js docs/public/d3-hexbin.v1.js
cp -v ./build/d3.github.com/d3-hexbin.v1.min.js docs/public/d3-hexbin.v1.min.js
cp -v ./build/d3.github.com/d3-hierarchy.v0.1.js docs/public/d3-hierarchy.v0.1.js
cp -v ./build/d3.github.com/d3-hierarchy.v0.1.min.js docs/public/d3-hierarchy.v0.1.min.js
cp -v ./build/d3.github.com/d3-hierarchy.v0.2.js docs/public/d3-hierarchy.v0.2.js
cp -v ./build/d3.github.com/d3-hierarchy.v0.2.min.js docs/public/d3-hierarchy.v0.2.min.js
cp -v ./build/d3.github.com/d3-hierarchy.v0.3.js docs/public/d3-hierarchy.v0.3.js
cp -v ./build/d3.github.com/d3-hierarchy.v0.3.min.js docs/public/d3-hierarchy.v0.3.min.js
cp -v ./build/d3.github.com/d3-hierarchy.v1.js docs/public/d3-hierarchy.v1.js
cp -v ./build/d3.github.com/d3-hierarchy.v1.min.js docs/public/d3-hierarchy.v1.min.js
cp -v ./build/d3.github.com/d3-hierarchy.v2.js docs/public/d3-hierarchy.v2.js
cp -v ./build/d3.github.com/d3-hierarchy.v2.min.js docs/public/d3-hierarchy.v2.min.js
cp -v ./build/d3.github.com/d3-hierarchy.v3.js docs/public/d3-hierarchy.v3.js
cp -v ./build/d3.github.com/d3-hierarchy.v3.min.js docs/public/d3-hierarchy.v3.min.js
cp -v ./build/d3.github.com/d3-hsv.v0.0.js docs/public/d3-hsv.v0.0.js
cp -v ./build/d3.github.com/d3-hsv.v0.0.min.js docs/public/d3-hsv.v0.0.min.js
cp -v ./build/d3.github.com/d3-hsv.v0.1.js docs/public/d3-hsv.v0.1.js
cp -v ./build/d3.github.com/d3-hsv.v0.1.min.js docs/public/d3-hsv.v0.1.min.js
cp -v ./build/d3.github.com/d3-interpolate.v0.2.js docs/public/d3-interpolate.v0.2.js
cp -v ./build/d3.github.com/d3-interpolate.v0.2.min.js docs/public/d3-interpolate.v0.2.min.js
cp -v ./build/d3.github.com/d3-interpolate.v0.3.js docs/public/d3-interpolate.v0.3.js
cp -v ./build/d3.github.com/d3-interpolate.v0.3.min.js docs/public/d3-interpolate.v0.3.min.js
cp -v ./build/d3.github.com/d3-interpolate.v0.4.js docs/public/d3-interpolate.v0.4.js
cp -v ./build/d3.github.com/d3-interpolate.v0.4.min.js docs/public/d3-interpolate.v0.4.min.js
cp -v ./build/d3.github.com/d3-interpolate.v0.5.js docs/public/d3-interpolate.v0.5.js
cp -v ./build/d3.github.com/d3-interpolate.v0.5.min.js docs/public/d3-interpolate.v0.5.min.js
cp -v ./build/d3.github.com/d3-interpolate.v0.6.js docs/public/d3-interpolate.v0.6.js
cp -v ./build/d3.github.com/d3-interpolate.v0.6.min.js docs/public/d3-interpolate.v0.6.min.js
cp -v ./build/d3.github.com/d3-interpolate.v0.7.js docs/public/d3-interpolate.v0.7.js
cp -v ./build/d3.github.com/d3-interpolate.v0.7.min.js docs/public/d3-interpolate.v0.7.min.js
cp -v ./build/d3.github.com/d3-interpolate.v0.8.js docs/public/d3-interpolate.v0.8.js
cp -v ./build/d3.github.com/d3-interpolate.v0.8.min.js docs/public/d3-interpolate.v0.8.min.js
cp -v ./build/d3.github.com/d3-interpolate.v0.9.js docs/public/d3-interpolate.v0.9.js
cp -v ./build/d3.github.com/d3-interpolate.v0.9.min.js docs/public/d3-interpolate.v0.9.min.js
cp -v ./build/d3.github.com/d3-interpolate.v1.js docs/public/d3-interpolate.v1.js
cp -v ./build/d3.github.com/d3-interpolate.v1.min.js docs/public/d3-interpolate.v1.min.js
cp -v ./build/d3.github.com/d3-interpolate.v2.js docs/public/d3-interpolate.v2.js
cp -v ./build/d3.github.com/d3-interpolate.v2.min.js docs/public/d3-interpolate.v2.min.js
cp -v ./build/d3.github.com/d3-interpolate.v3.js docs/public/d3-interpolate.v3.js
cp -v ./build/d3.github.com/d3-interpolate.v3.min.js docs/public/d3-interpolate.v3.min.js
cp -v ./build/d3.github.com/d3-path.v0.1.js docs/public/d3-path.v0.1.js
cp -v ./build/d3.github.com/d3-path.v0.1.min.js docs/public/d3-path.v0.1.min.js
cp -v ./build/d3.github.com/d3-path.v0.2.js docs/public/d3-path.v0.2.js
cp -v ./build/d3.github.com/d3-path.v0.2.min.js docs/public/d3-path.v0.2.min.js
cp -v ./build/d3.github.com/d3-path.v1.js docs/public/d3-path.v1.js
cp -v ./build/d3.github.com/d3-path.v1.min.js docs/public/d3-path.v1.min.js
cp -v ./build/d3.github.com/d3-path.v2.js docs/public/d3-path.v2.js
cp -v ./build/d3.github.com/d3-path.v2.min.js docs/public/d3-path.v2.min.js
cp -v ./build/d3.github.com/d3-path.v3.js docs/public/d3-path.v3.js
cp -v ./build/d3.github.com/d3-path.v3.min.js docs/public/d3-path.v3.min.js
cp -v ./build/d3.github.com/d3-polygon.v0.1.js docs/public/d3-polygon.v0.1.js
cp -v ./build/d3.github.com/d3-polygon.v0.1.min.js docs/public/d3-polygon.v0.1.min.js
cp -v ./build/d3.github.com/d3-polygon.v0.2.js docs/public/d3-polygon.v0.2.js
cp -v ./build/d3.github.com/d3-polygon.v0.2.min.js docs/public/d3-polygon.v0.2.min.js
cp -v ./build/d3.github.com/d3-polygon.v0.3.js docs/public/d3-polygon.v0.3.js
cp -v ./build/d3.github.com/d3-polygon.v0.3.min.js docs/public/d3-polygon.v0.3.min.js
cp -v ./build/d3.github.com/d3-polygon.v1.js docs/public/d3-polygon.v1.js
cp -v ./build/d3.github.com/d3-polygon.v1.min.js docs/public/d3-polygon.v1.min.js
cp -v ./build/d3.github.com/d3-polygon.v2.js docs/public/d3-polygon.v2.js
cp -v ./build/d3.github.com/d3-polygon.v2.min.js docs/public/d3-polygon.v2.min.js
cp -v ./build/d3.github.com/d3-polygon.v3.js docs/public/d3-polygon.v3.js
cp -v ./build/d3.github.com/d3-polygon.v3.min.js docs/public/d3-polygon.v3.min.js
cp -v ./build/d3.github.com/d3-quadtree.v0.1.js docs/public/d3-quadtree.v0.1.js
cp -v ./build/d3.github.com/d3-quadtree.v0.1.min.js docs/public/d3-quadtree.v0.1.min.js
cp -v ./build/d3.github.com/d3-quadtree.v0.2.js docs/public/d3-quadtree.v0.2.js
cp -v ./build/d3.github.com/d3-quadtree.v0.2.min.js docs/public/d3-quadtree.v0.2.min.js
cp -v ./build/d3.github.com/d3-quadtree.v0.3.js docs/public/d3-quadtree.v0.3.js
cp -v ./build/d3.github.com/d3-quadtree.v0.3.min.js docs/public/d3-quadtree.v0.3.min.js
cp -v ./build/d3.github.com/d3-quadtree.v0.4.js docs/public/d3-quadtree.v0.4.js
cp -v ./build/d3.github.com/d3-quadtree.v0.4.min.js docs/public/d3-quadtree.v0.4.min.js
cp -v ./build/d3.github.com/d3-quadtree.v0.5.js docs/public/d3-quadtree.v0.5.js
cp -v ./build/d3.github.com/d3-quadtree.v0.5.min.js docs/public/d3-quadtree.v0.5.min.js
cp -v ./build/d3.github.com/d3-quadtree.v0.6.js docs/public/d3-quadtree.v0.6.js
cp -v ./build/d3.github.com/d3-quadtree.v0.6.min.js docs/public/d3-quadtree.v0.6.min.js
cp -v ./build/d3.github.com/d3-quadtree.v0.7.js docs/public/d3-quadtree.v0.7.js
cp -v ./build/d3.github.com/d3-quadtree.v0.7.min.js docs/public/d3-quadtree.v0.7.min.js
cp -v ./build/d3.github.com/d3-quadtree.v0.8.js docs/public/d3-quadtree.v0.8.js
cp -v ./build/d3.github.com/d3-quadtree.v0.8.min.js docs/public/d3-quadtree.v0.8.min.js
cp -v ./build/d3.github.com/d3-quadtree.v1.js docs/public/d3-quadtree.v1.js
cp -v ./build/d3.github.com/d3-quadtree.v1.min.js docs/public/d3-quadtree.v1.min.js
cp -v ./build/d3.github.com/d3-quadtree.v2.js docs/public/d3-quadtree.v2.js
cp -v ./build/d3.github.com/d3-quadtree.v2.min.js docs/public/d3-quadtree.v2.min.js
cp -v ./build/d3.github.com/d3-quadtree.v3.js docs/public/d3-quadtree.v3.js
cp -v ./build/d3.github.com/d3-quadtree.v3.min.js docs/public/d3-quadtree.v3.min.js
cp -v ./build/d3.github.com/d3-queue.v1.js docs/public/d3-queue.v1.js
cp -v ./build/d3.github.com/d3-queue.v1.min.js docs/public/d3-queue.v1.min.js
cp -v ./build/d3.github.com/d3-queue.v2.js docs/public/d3-queue.v2.js
cp -v ./build/d3.github.com/d3-queue.v2.min.js docs/public/d3-queue.v2.min.js
cp -v ./build/d3.github.com/d3-queue.v3.js docs/public/d3-queue.v3.js
cp -v ./build/d3.github.com/d3-queue.v3.min.js docs/public/d3-queue.v3.min.js
cp -v ./build/d3.github.com/d3-random.v0.1.js docs/public/d3-random.v0.1.js
cp -v ./build/d3.github.com/d3-random.v0.1.min.js docs/public/d3-random.v0.1.min.js
cp -v ./build/d3.github.com/d3-random.v0.2.js docs/public/d3-random.v0.2.js
cp -v ./build/d3.github.com/d3-random.v0.2.min.js docs/public/d3-random.v0.2.min.js
cp -v ./build/d3.github.com/d3-random.v0.3.js docs/public/d3-random.v0.3.js
cp -v ./build/d3.github.com/d3-random.v0.3.min.js docs/public/d3-random.v0.3.min.js
cp -v ./build/d3.github.com/d3-random.v1.js docs/public/d3-random.v1.js
cp -v ./build/d3.github.com/d3-random.v1.min.js docs/public/d3-random.v1.min.js
cp -v ./build/d3.github.com/d3-random.v2.js docs/public/d3-random.v2.js
cp -v ./build/d3.github.com/d3-random.v2.min.js docs/public/d3-random.v2.min.js
cp -v ./build/d3.github.com/d3-random.v3.js docs/public/d3-random.v3.js
cp -v ./build/d3.github.com/d3-random.v3.min.js docs/public/d3-random.v3.min.js
cp -v ./build/d3.github.com/d3-request.v0.2.js docs/public/d3-request.v0.2.js
cp -v ./build/d3.github.com/d3-request.v0.2.min.js docs/public/d3-request.v0.2.min.js
cp -v ./build/d3.github.com/d3-request.v0.3.js docs/public/d3-request.v0.3.js
cp -v ./build/d3.github.com/d3-request.v0.3.min.js docs/public/d3-request.v0.3.min.js
cp -v ./build/d3.github.com/d3-request.v0.4.js docs/public/d3-request.v0.4.js
cp -v ./build/d3.github.com/d3-request.v0.4.min.js docs/public/d3-request.v0.4.min.js
cp -v ./build/d3.github.com/d3-request.v0.5.js docs/public/d3-request.v0.5.js
cp -v ./build/d3.github.com/d3-request.v0.5.min.js docs/public/d3-request.v0.5.min.js
cp -v ./build/d3.github.com/d3-request.v1.js docs/public/d3-request.v1.js
cp -v ./build/d3.github.com/d3-request.v1.min.js docs/public/d3-request.v1.min.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v0.0.js docs/public/d3-scale-chromatic.v0.0.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v0.0.min.js docs/public/d3-scale-chromatic.v0.0.min.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v0.1.js docs/public/d3-scale-chromatic.v0.1.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v0.1.min.js docs/public/d3-scale-chromatic.v0.1.min.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v0.2.js docs/public/d3-scale-chromatic.v0.2.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v0.2.min.js docs/public/d3-scale-chromatic.v0.2.min.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v0.3.js docs/public/d3-scale-chromatic.v0.3.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v0.3.min.js docs/public/d3-scale-chromatic.v0.3.min.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v1.js docs/public/d3-scale-chromatic.v1.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v1.min.js docs/public/d3-scale-chromatic.v1.min.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v2.js docs/public/d3-scale-chromatic.v2.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v2.min.js docs/public/d3-scale-chromatic.v2.min.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v3.js docs/public/d3-scale-chromatic.v3.js
cp -v ./build/d3.github.com/d3-scale-chromatic.v3.min.js docs/public/d3-scale-chromatic.v3.min.js
cp -v ./build/d3.github.com/d3-scale.v0.3.js docs/public/d3-scale.v0.3.js
cp -v ./build/d3.github.com/d3-scale.v0.3.min.js docs/public/d3-scale.v0.3.min.js
cp -v ./build/d3.github.com/d3-scale.v0.4.js docs/public/d3-scale.v0.4.js
cp -v ./build/d3.github.com/d3-scale.v0.4.min.js docs/public/d3-scale.v0.4.min.js
cp -v ./build/d3.github.com/d3-scale.v0.5.js docs/public/d3-scale.v0.5.js
cp -v ./build/d3.github.com/d3-scale.v0.5.min.js docs/public/d3-scale.v0.5.min.js
cp -v ./build/d3.github.com/d3-scale.v0.6.js docs/public/d3-scale.v0.6.js
cp -v ./build/d3.github.com/d3-scale.v0.6.min.js docs/public/d3-scale.v0.6.min.js
cp -v ./build/d3.github.com/d3-scale.v0.7.js docs/public/d3-scale.v0.7.js
cp -v ./build/d3.github.com/d3-scale.v0.7.min.js docs/public/d3-scale.v0.7.min.js
cp -v ./build/d3.github.com/d3-scale.v0.8.js docs/public/d3-scale.v0.8.js
cp -v ./build/d3.github.com/d3-scale.v0.8.min.js docs/public/d3-scale.v0.8.min.js
cp -v ./build/d3.github.com/d3-scale.v0.9.js docs/public/d3-scale.v0.9.js
cp -v ./build/d3.github.com/d3-scale.v0.9.min.js docs/public/d3-scale.v0.9.min.js
cp -v ./build/d3.github.com/d3-scale.v1.js docs/public/d3-scale.v1.js
cp -v ./build/d3.github.com/d3-scale.v1.min.js docs/public/d3-scale.v1.min.js
cp -v ./build/d3.github.com/d3-scale.v2.js docs/public/d3-scale.v2.js
cp -v ./build/d3.github.com/d3-scale.v2.min.js docs/public/d3-scale.v2.min.js
cp -v ./build/d3.github.com/d3-scale.v3.js docs/public/d3-scale.v3.js
cp -v ./build/d3.github.com/d3-scale.v3.min.js docs/public/d3-scale.v3.min.js
cp -v ./build/d3.github.com/d3-scale.v4.js docs/public/d3-scale.v4.js
cp -v ./build/d3.github.com/d3-scale.v4.min.js docs/public/d3-scale.v4.min.js
cp -v ./build/d3.github.com/d3-selection-multi.v0.2.js docs/public/d3-selection-multi.v0.2.js
cp -v ./build/d3.github.com/d3-selection-multi.v0.2.min.js docs/public/d3-selection-multi.v0.2.min.js
cp -v ./build/d3.github.com/d3-selection-multi.v0.3.js docs/public/d3-selection-multi.v0.3.js
cp -v ./build/d3.github.com/d3-selection-multi.v0.3.min.js docs/public/d3-selection-multi.v0.3.min.js
cp -v ./build/d3.github.com/d3-selection-multi.v0.4.js docs/public/d3-selection-multi.v0.4.js
cp -v ./build/d3.github.com/d3-selection-multi.v0.4.min.js docs/public/d3-selection-multi.v0.4.min.js
cp -v ./build/d3.github.com/d3-selection-multi.v1.js docs/public/d3-selection-multi.v1.js
cp -v ./build/d3.github.com/d3-selection-multi.v1.min.js docs/public/d3-selection-multi.v1.min.js
cp -v ./build/d3.github.com/d3-selection.v0.5.js docs/public/d3-selection.v0.5.js
cp -v ./build/d3.github.com/d3-selection.v0.5.min.js docs/public/d3-selection.v0.5.min.js
cp -v ./build/d3.github.com/d3-selection.v0.6.js docs/public/d3-selection.v0.6.js
cp -v ./build/d3.github.com/d3-selection.v0.6.min.js docs/public/d3-selection.v0.6.min.js
cp -v ./build/d3.github.com/d3-selection.v0.7.js docs/public/d3-selection.v0.7.js
cp -v ./build/d3.github.com/d3-selection.v0.7.min.js docs/public/d3-selection.v0.7.min.js
cp -v ./build/d3.github.com/d3-selection.v0.8.js docs/public/d3-selection.v0.8.js
cp -v ./build/d3.github.com/d3-selection.v0.8.min.js docs/public/d3-selection.v0.8.min.js
cp -v ./build/d3.github.com/d3-selection.v0.9.js docs/public/d3-selection.v0.9.js
cp -v ./build/d3.github.com/d3-selection.v0.9.min.js docs/public/d3-selection.v0.9.min.js
cp -v ./build/d3.github.com/d3-selection.v1.js docs/public/d3-selection.v1.js
cp -v ./build/d3.github.com/d3-selection.v1.min.js docs/public/d3-selection.v1.min.js
cp -v ./build/d3.github.com/d3-selection.v2.js docs/public/d3-selection.v2.js
cp -v ./build/d3.github.com/d3-selection.v2.min.js docs/public/d3-selection.v2.min.js
cp -v ./build/d3.github.com/d3-selection.v3.js docs/public/d3-selection.v3.js
cp -v ./build/d3.github.com/d3-selection.v3.min.js docs/public/d3-selection.v3.min.js
cp -v ./build/d3.github.com/d3-shape.v0.2.js docs/public/d3-shape.v0.2.js
cp -v ./build/d3.github.com/d3-shape.v0.2.min.js docs/public/d3-shape.v0.2.min.js
cp -v ./build/d3.github.com/d3-shape.v0.3.js docs/public/d3-shape.v0.3.js
cp -v ./build/d3.github.com/d3-shape.v0.3.min.js docs/public/d3-shape.v0.3.min.js
cp -v ./build/d3.github.com/d3-shape.v0.4.js docs/public/d3-shape.v0.4.js
cp -v ./build/d3.github.com/d3-shape.v0.4.min.js docs/public/d3-shape.v0.4.min.js
cp -v ./build/d3.github.com/d3-shape.v0.5.js docs/public/d3-shape.v0.5.js
cp -v ./build/d3.github.com/d3-shape.v0.5.min.js docs/public/d3-shape.v0.5.min.js
cp -v ./build/d3.github.com/d3-shape.v0.6.js docs/public/d3-shape.v0.6.js
cp -v ./build/d3.github.com/d3-shape.v0.6.min.js docs/public/d3-shape.v0.6.min.js
cp -v ./build/d3.github.com/d3-shape.v0.7.js docs/public/d3-shape.v0.7.js
cp -v ./build/d3.github.com/d3-shape.v0.7.min.js docs/public/d3-shape.v0.7.min.js
cp -v ./build/d3.github.com/d3-shape.v1.js docs/public/d3-shape.v1.js
cp -v ./build/d3.github.com/d3-shape.v1.min.js docs/public/d3-shape.v1.min.js
cp -v ./build/d3.github.com/d3-shape.v2.js docs/public/d3-shape.v2.js
cp -v ./build/d3.github.com/d3-shape.v2.min.js docs/public/d3-shape.v2.min.js
cp -v ./build/d3.github.com/d3-shape.v3.js docs/public/d3-shape.v3.js
cp -v ./build/d3.github.com/d3-shape.v3.min.js docs/public/d3-shape.v3.min.js
cp -v ./build/d3.github.com/d3-tile.v0.0.js docs/public/d3-tile.v0.0.js
cp -v ./build/d3.github.com/d3-tile.v0.0.min.js docs/public/d3-tile.v0.0.min.js
cp -v ./build/d3.github.com/d3-time-format.v0.2.js docs/public/d3-time-format.v0.2.js
cp -v ./build/d3.github.com/d3-time-format.v0.2.min.js docs/public/d3-time-format.v0.2.min.js
cp -v ./build/d3.github.com/d3-time-format.v0.3.js docs/public/d3-time-format.v0.3.js
cp -v ./build/d3.github.com/d3-time-format.v0.3.min.js docs/public/d3-time-format.v0.3.min.js
cp -v ./build/d3.github.com/d3-time-format.v0.4.js docs/public/d3-time-format.v0.4.js
cp -v ./build/d3.github.com/d3-time-format.v0.4.min.js docs/public/d3-time-format.v0.4.min.js
cp -v ./build/d3.github.com/d3-time-format.v1.js docs/public/d3-time-format.v1.js
cp -v ./build/d3.github.com/d3-time-format.v1.min.js docs/public/d3-time-format.v1.min.js
cp -v ./build/d3.github.com/d3-time-format.v2.js docs/public/d3-time-format.v2.js
cp -v ./build/d3.github.com/d3-time-format.v2.min.js docs/public/d3-time-format.v2.min.js
cp -v ./build/d3.github.com/d3-time-format.v3.js docs/public/d3-time-format.v3.js
cp -v ./build/d3.github.com/d3-time-format.v3.min.js docs/public/d3-time-format.v3.min.js
cp -v ./build/d3.github.com/d3-time-format.v4.js docs/public/d3-time-format.v4.js
cp -v ./build/d3.github.com/d3-time-format.v4.min.js docs/public/d3-time-format.v4.min.js
cp -v ./build/d3.github.com/d3-time.v0.1.js docs/public/d3-time.v0.1.js
cp -v ./build/d3.github.com/d3-time.v0.1.min.js docs/public/d3-time.v0.1.min.js
cp -v ./build/d3.github.com/d3-time.v0.2.js docs/public/d3-time.v0.2.js
cp -v ./build/d3.github.com/d3-time.v0.2.min.js docs/public/d3-time.v0.2.min.js
cp -v ./build/d3.github.com/d3-time.v0.3.js docs/public/d3-time.v0.3.js
cp -v ./build/d3.github.com/d3-time.v0.3.min.js docs/public/d3-time.v0.3.min.js
cp -v ./build/d3.github.com/d3-time.v1.js docs/public/d3-time.v1.js
cp -v ./build/d3.github.com/d3-time.v1.min.js docs/public/d3-time.v1.min.js
cp -v ./build/d3.github.com/d3-time.v2.js docs/public/d3-time.v2.js
cp -v ./build/d3.github.com/d3-time.v2.min.js docs/public/d3-time.v2.min.js
cp -v ./build/d3.github.com/d3-time.v3.js docs/public/d3-time.v3.js
cp -v ./build/d3.github.com/d3-time.v3.min.js docs/public/d3-time.v3.min.js
cp -v ./build/d3.github.com/d3-timer.v0.1.js docs/public/d3-timer.v0.1.js
cp -v ./build/d3.github.com/d3-timer.v0.1.min.js docs/public/d3-timer.v0.1.min.js
cp -v ./build/d3.github.com/d3-timer.v0.2.js docs/public/d3-timer.v0.2.js
cp -v ./build/d3.github.com/d3-timer.v0.2.min.js docs/public/d3-timer.v0.2.min.js
cp -v ./build/d3.github.com/d3-timer.v0.3.js docs/public/d3-timer.v0.3.js
cp -v ./build/d3.github.com/d3-timer.v0.3.min.js docs/public/d3-timer.v0.3.min.js
cp -v ./build/d3.github.com/d3-timer.v0.4.js docs/public/d3-timer.v0.4.js
cp -v ./build/d3.github.com/d3-timer.v0.4.min.js docs/public/d3-timer.v0.4.min.js
cp -v ./build/d3.github.com/d3-timer.v0.5.js docs/public/d3-timer.v0.5.js
cp -v ./build/d3.github.com/d3-timer.v0.5.min.js docs/public/d3-timer.v0.5.min.js
cp -v ./build/d3.github.com/d3-timer.v1.js docs/public/d3-timer.v1.js
cp -v ./build/d3.github.com/d3-timer.v1.min.js docs/public/d3-timer.v1.min.js
cp -v ./build/d3.github.com/d3-timer.v2.js docs/public/d3-timer.v2.js
cp -v ./build/d3.github.com/d3-timer.v2.min.js docs/public/d3-timer.v2.min.js
cp -v ./build/d3.github.com/d3-timer.v3.js docs/public/d3-timer.v3.js
cp -v ./build/d3.github.com/d3-timer.v3.min.js docs/public/d3-timer.v3.min.js
cp -v ./build/d3.github.com/d3-transition.v0.0.js docs/public/d3-transition.v0.0.js
cp -v ./build/d3.github.com/d3-transition.v0.0.min.js docs/public/d3-transition.v0.0.min.js
cp -v ./build/d3.github.com/d3-transition.v0.1.js docs/public/d3-transition.v0.1.js
cp -v ./build/d3.github.com/d3-transition.v0.1.min.js docs/public/d3-transition.v0.1.min.js
cp -v ./build/d3.github.com/d3-transition.v0.2.js docs/public/d3-transition.v0.2.js
cp -v ./build/d3.github.com/d3-transition.v0.2.min.js docs/public/d3-transition.v0.2.min.js
cp -v ./build/d3.github.com/d3-transition.v0.3.js docs/public/d3-transition.v0.3.js
cp -v ./build/d3.github.com/d3-transition.v0.3.min.js docs/public/d3-transition.v0.3.min.js
cp -v ./build/d3.github.com/d3-transition.v1.js docs/public/d3-transition.v1.js
cp -v ./build/d3.github.com/d3-transition.v1.min.js docs/public/d3-transition.v1.min.js
cp -v ./build/d3.github.com/d3-transition.v2.js docs/public/d3-transition.v2.js
cp -v ./build/d3.github.com/d3-transition.v2.min.js docs/public/d3-transition.v2.min.js
cp -v ./build/d3.github.com/d3-transition.v3.js docs/public/d3-transition.v3.js
cp -v ./build/d3.github.com/d3-transition.v3.min.js docs/public/d3-transition.v3.min.js
cp -v ./build/d3.github.com/d3-voronoi.v0.1.js docs/public/d3-voronoi.v0.1.js
cp -v ./build/d3.github.com/d3-voronoi.v0.1.min.js docs/public/d3-voronoi.v0.1.min.js
cp -v ./build/d3.github.com/d3-voronoi.v0.2.js docs/public/d3-voronoi.v0.2.js
cp -v ./build/d3.github.com/d3-voronoi.v0.2.min.js docs/public/d3-voronoi.v0.2.min.js
cp -v ./build/d3.github.com/d3-voronoi.v0.3.js docs/public/d3-voronoi.v0.3.js
cp -v ./build/d3.github.com/d3-voronoi.v0.3.min.js docs/public/d3-voronoi.v0.3.min.js
cp -v ./build/d3.github.com/d3-voronoi.v0.4.js docs/public/d3-voronoi.v0.4.js
cp -v ./build/d3.github.com/d3-voronoi.v0.4.min.js docs/public/d3-voronoi.v0.4.min.js
cp -v ./build/d3.github.com/d3-voronoi.v1.js docs/public/d3-voronoi.v1.js
cp -v ./build/d3.github.com/d3-voronoi.v1.min.js docs/public/d3-voronoi.v1.min.js
cp -v ./build/d3.github.com/d3-zoom.v0.0.js docs/public/d3-zoom.v0.0.js
cp -v ./build/d3.github.com/d3-zoom.v0.0.min.js docs/public/d3-zoom.v0.0.min.js
cp -v ./build/d3.github.com/d3-zoom.v0.1.js docs/public/d3-zoom.v0.1.js
cp -v ./build/d3.github.com/d3-zoom.v0.1.min.js docs/public/d3-zoom.v0.1.min.js
cp -v ./build/d3.github.com/d3-zoom.v0.2.js docs/public/d3-zoom.v0.2.js
cp -v ./build/d3.github.com/d3-zoom.v0.2.min.js docs/public/d3-zoom.v0.2.min.js
cp -v ./build/d3.github.com/d3-zoom.v0.3.js docs/public/d3-zoom.v0.3.js
cp -v ./build/d3.github.com/d3-zoom.v0.3.min.js docs/public/d3-zoom.v0.3.min.js
cp -v ./build/d3.github.com/d3-zoom.v1.js docs/public/d3-zoom.v1.js
cp -v ./build/d3.github.com/d3-zoom.v1.min.js docs/public/d3-zoom.v1.min.js
cp -v ./build/d3.github.com/d3-zoom.v2.js docs/public/d3-zoom.v2.js
cp -v ./build/d3.github.com/d3-zoom.v2.min.js docs/public/d3-zoom.v2.min.js
cp -v ./build/d3.github.com/d3-zoom.v3.js docs/public/d3-zoom.v3.js
cp -v ./build/d3.github.com/d3-zoom.v3.min.js docs/public/d3-zoom.v3.min.js
cp -v ./build/d3.github.com/d3.geo.polyhedron.v0.js docs/public/d3.geo.polyhedron.v0.js
cp -v ./build/d3.github.com/d3.geo.polyhedron.v0.min.js docs/public/d3.geo.polyhedron.v0.min.js
cp -v ./build/d3.github.com/d3.geo.projection.v0.js docs/public/d3.geo.projection.v0.js
cp -v ./build/d3.github.com/d3.geo.projection.v0.min.js docs/public/d3.geo.projection.v0.min.js
cp -v ./build/d3.github.com/d3.geo.tile.v0.js docs/public/d3.geo.tile.v0.js
cp -v ./build/d3.github.com/d3.geo.tile.v0.min.js docs/public/d3.geo.tile.v0.min.js
cp -v ./build/d3.github.com/d3.geodesic.v0.js docs/public/d3.geodesic.v0.js
cp -v ./build/d3.github.com/d3.geodesic.v0.min.js docs/public/d3.geodesic.v0.min.js
cp -v ./build/d3.github.com/d3.geom.contour.v0.js docs/public/d3.geom.contour.v0.js
cp -v ./build/d3.github.com/d3.geom.contour.v0.min.js docs/public/d3.geom.contour.v0.min.js
cp -v ./build/d3.github.com/d3.hexbin.v0.js docs/public/d3.hexbin.v0.js
cp -v ./build/d3.github.com/d3.hexbin.v0.min.js docs/public/d3.hexbin.v0.min.js
cp -v ./build/d3.github.com/d3.hive.v0.js docs/public/d3.hive.v0.js
cp -v ./build/d3.github.com/d3.hive.v0.min.js docs/public/d3.hive.v0.min.js
cp -v ./build/d3.github.com/d3.interpolate-zoom.v0.js docs/public/d3.interpolate-zoom.v0.js
cp -v ./build/d3.github.com/d3.interpolate-zoom.v0.min.js docs/public/d3.interpolate-zoom.v0.min.js
cp -v ./build/d3.github.com/d3.qq.v0.js docs/public/d3.qq.v0.js
cp -v ./build/d3.github.com/d3.qq.v0.min.js docs/public/d3.qq.v0.min.js
cp -v ./build/d3.github.com/d3.rollup.v0.js docs/public/d3.rollup.v0.js
cp -v ./build/d3.github.com/d3.rollup.v0.min.js docs/public/d3.rollup.v0.min.js
cp -v ./build/d3.github.com/d3.superformula.v0.js docs/public/d3.superformula.v0.js
cp -v ./build/d3.github.com/d3.superformula.v0.min.js docs/public/d3.superformula.v0.min.js
cp -v ./build/d3.github.com/d3.v2.js docs/public/d3.v2.js
cp -v ./build/d3.github.com/d3.v2.min.js docs/public/d3.v2.min.js
cp -v ./build/d3.github.com/d3.v3.js docs/public/d3.v3.js
cp -v ./build/d3.github.com/d3.v3.min.js docs/public/d3.v3.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.1.js docs/public/d3.v4.0.0-alpha.1.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.1.min.js docs/public/d3.v4.0.0-alpha.1.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.10.js docs/public/d3.v4.0.0-alpha.10.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.10.min.js docs/public/d3.v4.0.0-alpha.10.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.11.js docs/public/d3.v4.0.0-alpha.11.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.11.min.js docs/public/d3.v4.0.0-alpha.11.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.12.js docs/public/d3.v4.0.0-alpha.12.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.12.min.js docs/public/d3.v4.0.0-alpha.12.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.13.js docs/public/d3.v4.0.0-alpha.13.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.13.min.js docs/public/d3.v4.0.0-alpha.13.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.14.js docs/public/d3.v4.0.0-alpha.14.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.14.min.js docs/public/d3.v4.0.0-alpha.14.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.15.js docs/public/d3.v4.0.0-alpha.15.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.15.min.js docs/public/d3.v4.0.0-alpha.15.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.16.js docs/public/d3.v4.0.0-alpha.16.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.16.min.js docs/public/d3.v4.0.0-alpha.16.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.17.js docs/public/d3.v4.0.0-alpha.17.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.17.min.js docs/public/d3.v4.0.0-alpha.17.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.18.js docs/public/d3.v4.0.0-alpha.18.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.18.min.js docs/public/d3.v4.0.0-alpha.18.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.19.js docs/public/d3.v4.0.0-alpha.19.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.19.min.js docs/public/d3.v4.0.0-alpha.19.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.2.js docs/public/d3.v4.0.0-alpha.2.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.2.min.js docs/public/d3.v4.0.0-alpha.2.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.20.js docs/public/d3.v4.0.0-alpha.20.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.20.min.js docs/public/d3.v4.0.0-alpha.20.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.21.js docs/public/d3.v4.0.0-alpha.21.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.21.min.js docs/public/d3.v4.0.0-alpha.21.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.22.js docs/public/d3.v4.0.0-alpha.22.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.22.min.js docs/public/d3.v4.0.0-alpha.22.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.23.js docs/public/d3.v4.0.0-alpha.23.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.23.min.js docs/public/d3.v4.0.0-alpha.23.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.24.js docs/public/d3.v4.0.0-alpha.24.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.24.min.js docs/public/d3.v4.0.0-alpha.24.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.26.js docs/public/d3.v4.0.0-alpha.26.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.26.min.js docs/public/d3.v4.0.0-alpha.26.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.27.js docs/public/d3.v4.0.0-alpha.27.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.27.min.js docs/public/d3.v4.0.0-alpha.27.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.28.js docs/public/d3.v4.0.0-alpha.28.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.28.min.js docs/public/d3.v4.0.0-alpha.28.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.29.js docs/public/d3.v4.0.0-alpha.29.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.29.min.js docs/public/d3.v4.0.0-alpha.29.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.3.js docs/public/d3.v4.0.0-alpha.3.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.3.min.js docs/public/d3.v4.0.0-alpha.3.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.30.js docs/public/d3.v4.0.0-alpha.30.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.30.min.js docs/public/d3.v4.0.0-alpha.30.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.31.js docs/public/d3.v4.0.0-alpha.31.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.31.min.js docs/public/d3.v4.0.0-alpha.31.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.32.js docs/public/d3.v4.0.0-alpha.32.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.32.min.js docs/public/d3.v4.0.0-alpha.32.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.33.js docs/public/d3.v4.0.0-alpha.33.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.33.min.js docs/public/d3.v4.0.0-alpha.33.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.34.js docs/public/d3.v4.0.0-alpha.34.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.34.min.js docs/public/d3.v4.0.0-alpha.34.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.35.js docs/public/d3.v4.0.0-alpha.35.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.35.min.js docs/public/d3.v4.0.0-alpha.35.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.36.js docs/public/d3.v4.0.0-alpha.36.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.36.min.js docs/public/d3.v4.0.0-alpha.36.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.37.js docs/public/d3.v4.0.0-alpha.37.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.37.min.js docs/public/d3.v4.0.0-alpha.37.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.38.js docs/public/d3.v4.0.0-alpha.38.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.38.min.js docs/public/d3.v4.0.0-alpha.38.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.39.js docs/public/d3.v4.0.0-alpha.39.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.39.min.js docs/public/d3.v4.0.0-alpha.39.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.4.js docs/public/d3.v4.0.0-alpha.4.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.4.min.js docs/public/d3.v4.0.0-alpha.4.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.40.js docs/public/d3.v4.0.0-alpha.40.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.40.min.js docs/public/d3.v4.0.0-alpha.40.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.41.js docs/public/d3.v4.0.0-alpha.41.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.41.min.js docs/public/d3.v4.0.0-alpha.41.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.42.js docs/public/d3.v4.0.0-alpha.42.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.42.min.js docs/public/d3.v4.0.0-alpha.42.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.43.js docs/public/d3.v4.0.0-alpha.43.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.43.min.js docs/public/d3.v4.0.0-alpha.43.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.44.js docs/public/d3.v4.0.0-alpha.44.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.44.min.js docs/public/d3.v4.0.0-alpha.44.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.45.js docs/public/d3.v4.0.0-alpha.45.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.45.min.js docs/public/d3.v4.0.0-alpha.45.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.46.js docs/public/d3.v4.0.0-alpha.46.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.46.min.js docs/public/d3.v4.0.0-alpha.46.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.47.js docs/public/d3.v4.0.0-alpha.47.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.47.min.js docs/public/d3.v4.0.0-alpha.47.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.48.js docs/public/d3.v4.0.0-alpha.48.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.48.min.js docs/public/d3.v4.0.0-alpha.48.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.49.js docs/public/d3.v4.0.0-alpha.49.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.49.min.js docs/public/d3.v4.0.0-alpha.49.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.5.js docs/public/d3.v4.0.0-alpha.5.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.5.min.js docs/public/d3.v4.0.0-alpha.5.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.50.js docs/public/d3.v4.0.0-alpha.50.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.50.min.js docs/public/d3.v4.0.0-alpha.50.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.6.js docs/public/d3.v4.0.0-alpha.6.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.6.min.js docs/public/d3.v4.0.0-alpha.6.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.7.js docs/public/d3.v4.0.0-alpha.7.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.7.min.js docs/public/d3.v4.0.0-alpha.7.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.8.js docs/public/d3.v4.0.0-alpha.8.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.8.min.js docs/public/d3.v4.0.0-alpha.8.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.9.js docs/public/d3.v4.0.0-alpha.9.js
cp -v ./build/d3.github.com/d3.v4.0.0-alpha.9.min.js docs/public/d3.v4.0.0-alpha.9.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-rc.1.js docs/public/d3.v4.0.0-rc.1.js
cp -v ./build/d3.github.com/d3.v4.0.0-rc.1.min.js docs/public/d3.v4.0.0-rc.1.min.js
cp -v ./build/d3.github.com/d3.v4.0.0-rc.2.js docs/public/d3.v4.0.0-rc.2.js
cp -v ./build/d3.github.com/d3.v4.0.0-rc.2.min.js docs/public/d3.v4.0.0-rc.2.min.js
cp -v ./build/d3.github.com/d3.v4.js docs/public/d3.v4.js
cp -v ./build/d3.github.com/d3.v4.min.js docs/public/d3.v4.min.js
cp -v ./build/d3.github.com/d3.v5.js docs/public/d3.v5.js
cp -v ./build/d3.github.com/d3.v5.min.js docs/public/d3.v5.min.js
cp -v ./build/d3.github.com/d3.v6.js docs/public/d3.v6.js
cp -v ./build/d3.github.com/d3.v6.min.js docs/public/d3.v6.min.js
cp -v ./build/d3.github.com/highlight.v0.min.js docs/public/highlight.v0.min.js
cp -v ./build/d3.github.com/highlight.v9.min.js docs/public/highlight.v9.min.js
cp -v ./build/d3.github.com/queue.v1.js docs/public/queue.v1.js
cp -v ./build/d3.github.com/queue.v1.min.js docs/public/queue.v1.min.js
cp -v ./build/d3.github.com/topojson.v0.js docs/public/topojson.v0.js
cp -v ./build/d3.github.com/topojson.v0.min.js docs/public/topojson.v0.min.js
cp -v ./build/d3.github.com/topojson.v1.js docs/public/topojson.v1.js
cp -v ./build/d3.github.com/topojson.v1.min.js docs/public/topojson.v1.min.js
cp -v ./build/d3.github.com/topojson.v2.js docs/public/topojson.v2.js
cp -v ./build/d3.github.com/topojson.v2.min.js docs/public/topojson.v2.min.js
cp -v ./build/d3.github.com/topojson.v3.js docs/public/topojson.v3.js
cp -v ./build/d3.github.com/topojson.v3.min.js docs/public/topojson.v3.min.js
cp -v ./build/d3.github.com/us-10m.v0.json docs/public/us-10m.v0.json
cp -v ./build/d3.github.com/us-10m.v1.json docs/public/us-10m.v1.json
cp -v ./build/d3.github.com/us-10m.v2.json docs/public/us-10m.v2.json
cp -v ./build/d3.github.com/world-110m.v1.json docs/public/world-110m.v1.json
cp -v ./build/d3.github.com/world-110m.v1.tsv docs/public/world-110m.v1.tsv
cp -v ./build/d3.github.com/world-50m.v1.json docs/public/world-50m.v1.json
cp -v ./build/d3.github.com/world-50m.v1.tsv docs/public/world-50m.v1.tsv

cp -v ./dist/d3.js docs/public/d3.v7.js
cp -v ./dist/d3.min.js docs/public/d3.v7.min.js

cp -v ./node_modules/d3-array/dist/d3-array.js docs/public/d3-array.v3.js
cp -v ./node_modules/d3-array/dist/d3-array.min.js docs/public/d3-array.v3.min.js
cp -v ./node_modules/d3-axis/dist/d3-axis.js docs/public/d3-axis.v3.js
cp -v ./node_modules/d3-axis/dist/d3-axis.min.js docs/public/d3-axis.v3.min.js
cp -v ./node_modules/d3-brush/dist/d3-brush.js docs/public/d3-brush.v3.js
cp -v ./node_modules/d3-brush/dist/d3-brush.min.js docs/public/d3-brush.v3.min.js
cp -v ./node_modules/d3-chord/dist/d3-chord.js docs/public/d3-chord.v3.js
cp -v ./node_modules/d3-chord/dist/d3-chord.min.js docs/public/d3-chord.v3.min.js
cp -v ./node_modules/d3-color/dist/d3-color.js docs/public/d3-color.v3.js
cp -v ./node_modules/d3-color/dist/d3-color.min.js docs/public/d3-color.v3.min.js
cp -v ./node_modules/d3-contour/dist/d3-contour.js docs/public/d3-contour.v4.js
cp -v ./node_modules/d3-contour/dist/d3-contour.min.js docs/public/d3-contour.v4.min.js
cp -v ./node_modules/d3-delaunay/dist/d3-delaunay.js docs/public/d3-delaunay.v6.js
cp -v ./node_modules/d3-delaunay/dist/d3-delaunay.min.js docs/public/d3-delaunay.v6.min.js
cp -v ./node_modules/d3-dispatch/dist/d3-dispatch.js docs/public/d3-dispatch.v3.js
cp -v ./node_modules/d3-dispatch/dist/d3-dispatch.min.js docs/public/d3-dispatch.v3.min.js
cp -v ./node_modules/d3-drag/dist/d3-drag.js docs/public/d3-drag.v3.js
cp -v ./node_modules/d3-drag/dist/d3-drag.min.js docs/public/d3-drag.v3.min.js
cp -v ./node_modules/d3-dsv/dist/d3-dsv.js docs/public/d3-dsv.v3.js
cp -v ./node_modules/d3-dsv/dist/d3-dsv.min.js docs/public/d3-dsv.v3.min.js
cp -v ./node_modules/d3-ease/dist/d3-ease.js docs/public/d3-ease.v3.js
cp -v ./node_modules/d3-ease/dist/d3-ease.min.js docs/public/d3-ease.v3.min.js
cp -v ./node_modules/d3-fetch/dist/d3-fetch.js docs/public/d3-fetch.v3.js
cp -v ./node_modules/d3-fetch/dist/d3-fetch.min.js docs/public/d3-fetch.v3.min.js
cp -v ./node_modules/d3-force/dist/d3-force.js docs/public/d3-force.v3.js
cp -v ./node_modules/d3-force/dist/d3-force.min.js docs/public/d3-force.v3.min.js
cp -v ./node_modules/d3-format/dist/d3-format.js docs/public/d3-format.v3.js
cp -v ./node_modules/d3-format/dist/d3-format.min.js docs/public/d3-format.v3.min.js
cp -v ./node_modules/d3-geo/dist/d3-geo.js docs/public/d3-geo.v3.js
cp -v ./node_modules/d3-geo/dist/d3-geo.min.js docs/public/d3-geo.v3.min.js
cp -v ./node_modules/d3-hierarchy/dist/d3-hierarchy.js docs/public/d3-hierarchy.v3.js
cp -v ./node_modules/d3-hierarchy/dist/d3-hierarchy.min.js docs/public/d3-hierarchy.v3.min.js
cp -v ./node_modules/d3-interpolate/dist/d3-interpolate.js docs/public/d3-interpolate.v3.js
cp -v ./node_modules/d3-interpolate/dist/d3-interpolate.min.js docs/public/d3-interpolate.v3.min.js
cp -v ./node_modules/d3-path/dist/d3-path.js docs/public/d3-path.v3.js
cp -v ./node_modules/d3-path/dist/d3-path.min.js docs/public/d3-path.v3.min.js
cp -v ./node_modules/d3-polygon/dist/d3-polygon.js docs/public/d3-polygon.v3.js
cp -v ./node_modules/d3-polygon/dist/d3-polygon.min.js docs/public/d3-polygon.v3.min.js
cp -v ./node_modules/d3-quadtree/dist/d3-quadtree.js docs/public/d3-quadtree.v3.js
cp -v ./node_modules/d3-quadtree/dist/d3-quadtree.min.js docs/public/d3-quadtree.v3.min.js
cp -v ./node_modules/d3-random/dist/d3-random.js docs/public/d3-random.v3.js
cp -v ./node_modules/d3-random/dist/d3-random.min.js docs/public/d3-random.v3.min.js
cp -v ./node_modules/d3-scale-chromatic/dist/d3-scale-chromatic.js docs/public/d3-scale-chromatic.v3.js
cp -v ./node_modules/d3-scale-chromatic/dist/d3-scale-chromatic.min.js docs/public/d3-scale-chromatic.v3.min.js
cp -v ./node_modules/d3-scale/dist/d3-scale.js docs/public/d3-scale.v4.js
cp -v ./node_modules/d3-scale/dist/d3-scale.min.js docs/public/d3-scale.v4.min.js
cp -v ./node_modules/d3-selection/dist/d3-selection.js docs/public/d3-selection.v3.js
cp -v ./node_modules/d3-selection/dist/d3-selection.min.js docs/public/d3-selection.v3.min.js
cp -v ./node_modules/d3-shape/dist/d3-shape.js docs/public/d3-shape.v3.js
cp -v ./node_modules/d3-shape/dist/d3-shape.min.js docs/public/d3-shape.v3.min.js
cp -v ./node_modules/d3-time-format/dist/d3-time-format.js docs/public/d3-time-format.v4.js
cp -v ./node_modules/d3-time-format/dist/d3-time-format.min.js docs/public/d3-time-format.v4.min.js
cp -v ./node_modules/d3-time/dist/d3-time.js docs/public/d3-time.v3.js
cp -v ./node_modules/d3-time/dist/d3-time.min.js docs/public/d3-time.v3.min.js
cp -v ./node_modules/d3-timer/dist/d3-timer.js docs/public/d3-timer.v3.js
cp -v ./node_modules/d3-timer/dist/d3-timer.min.js docs/public/d3-timer.v3.min.js
cp -v ./node_modules/d3-transition/dist/d3-transition.js docs/public/d3-transition.v3.js
cp -v ./node_modules/d3-transition/dist/d3-transition.min.js docs/public/d3-transition.v3.min.js
cp -v ./node_modules/d3-zoom/dist/d3-zoom.js docs/public/d3-zoom.v3.js
cp -v ./node_modules/d3-zoom/dist/d3-zoom.min.js docs/public/d3-zoom.v3.min.js
